//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadatakA16c
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class A16Entities : DbContext
    {
        public A16Entities()
            : base("name=A16Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boja> Boja { get; set; }
        public virtual DbSet<Duzina_Dlake> Duzina_Dlake { get; set; }
        public virtual DbSet<Izlozba> Izlozba { get; set; }
        public virtual DbSet<Kategorija> Kategorija { get; set; }
        public virtual DbSet<Pas> Pas { get; set; }
        public virtual DbSet<Pol> Pol { get; set; }
        public virtual DbSet<Rasa> Rasa { get; set; }
        public virtual DbSet<Rezultat> Rezultat { get; set; }
        public virtual DbSet<Vlasnik> Vlasnik { get; set; }
    }
}
