//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadatakA16c
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pas()
        {
            this.Rezultat = new HashSet<Rezultat>();
        }
    
        public int PasID { get; set; }
        public string Ime { get; set; }
        public int Tezina { get; set; }
        public int DDID { get; set; }
        public int BojaID { get; set; }
        public int RasaID { get; set; }
        public bool Ostenjen { get; set; }
        public int VlasnikID { get; set; }
        public int PolID { get; set; }
    
        public virtual Boja Boja { get; set; }
        public virtual Duzina_Dlake Duzina_Dlake { get; set; }
        public virtual Pol Pol { get; set; }
        public virtual Rasa Rasa { get; set; }
        public virtual Vlasnik Vlasnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezultat> Rezultat { get; set; }
    }
}
